const projectsData = [
  // React Projects
  {
    id: 1,
    title: "FilmyWorld Movie App",
    desc: "React movie app with Redux and infinite scrolling.",
    category: "react",
    link: "https://react-filmyworld.netlify.app/",
    image: "assets/s-images/filmyworld.png",
    video: "assets/s-video/sample-5s.mp4",
  },
  {
    id: 2,
    title: "React E-Commerce App",
    desc: "React e-commerce app with Context API and CRUD.",
    category: "react",
    link: "https://reactproject-with-api.netlify.app/",
    image: "assets/s-images/REACT-2.png",
    video: "assets/s-video/react-e-comerce.mp4",
  },

  // HTML/CSS Projects
  {
    id: 3,
    title: "Dribbble Clone",
    desc: "Dribbble-style grid portfolio layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/13-dribble-clone",
    image: "assets/s-images/DRIBBLE.png",
    video: "assets/s-video/dribble.mp4",
  },
  {
    id: 4,
    title: "Winter Icecream Page",
    desc: "Icecream-themed landing page with animations.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/05-WINTER-SPECIAL-ICECREAM",
    image: "assets/s-images/ICECREAM.png",
    video: "assets/s-video/icecream.mp4",
  },
  {
    id: 5,
    title: "E-Commerce Landing",
    desc: "Basic e-commerce homepage with responsive layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/03-Ecommerce",
    image: "assets/s-images/CARA ATTRASCTIVE.png",
    video: "assets/s-video/cara.mp4",
  },
  {
    id: 6,
    title: "Blinkit UI Clone",
    desc: "Blinkit UI clone using grid & flexbox.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/02-blinkit-clone",
    image: "assets/s-images/BLINKIT.png",
    video: "assets/s-video/blinkit.mp4",
  },
  {
    id: 7,
    title: "e_learning Landing Page",
    desc: "Clean modern landing page with hero section.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/04-Landing-page",
    image: "assets/s-images/E-LEARNING.png",
    video: "assets/s-video/e-learning.mp4",
  },
  {
    id: 8,
    title: "Obys Agency Clone",
    desc: "Agency landing page with smooth sections.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/14-obys-agency-clone",
    image: "assets/s-images/OBYS.png",
    video: "assets/s-video/obys-agency.mp4",
  },
  {
    id: 9,
    title: "Product Designer Page",
    desc: "Portfolio-style page for designers.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/15-product-designer",
    image: "assets/s-images/producr-designere.png",
    video: "assets/s-video/product-designer.mp4",
  },
  {
    id: 10,
    title: "Porsche Landing Page",
    desc: "Car landing page with carousel hero.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/07-Porsche",
    image: "assets/s-images/PORSCHE.png",
    video: "assets/s-video/porshce.mp4",
  },
  {
    id: 11,
    title: "Cotton Landing Page",
    desc: "Cotton product page with clean layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/10-cotton-landing-page",
    image: "assets/s-images/cotton ladning page.png",
    video: "assets/s-video/cotton-landing-page.mp4",
  },
  {
    id: 12,
    title: "Hero Panther Page",
    desc: "Bold hero section inspired by Panther theme.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/20-Hero-Panther-landing-page",
    image: "assets/s-images/MARVEL.png",
    video: "assets/s-video/black-panther.mp4",
  },
  {
    id: 13,
    title: "Sheriyans Landing Page",
    desc: "Clean landing page with good typography.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/18-sheriyans-landig-page",
    image: "assets/s-images/sheriyans .png",
    video: "assets/s-video/sheriyans.mp4",
  },
  {
    id: 14,
    title: "Play Landing Page",
    desc: "Colorful landing page with fun elements.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/19-PLAY-landing-pages/",
    image: "assets/s-images/PLAY-KLANDINMG.png",
    video: "assets/s-video/play.mp4",
  },
  {
    id: 15,
    title: "Starbucks Landing Page",
    desc: "Starbucks-themed page with product showcase.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/08-Starbucks",
    image: "assets/s-images/STARBUCKS.png",
    video: "assets/s-video/starbucks.mp4",
  },
  {
    id: 16,
    title: "Premier Landing Page",
    desc: "Premium look landing page with hover effects.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/12-Premier landing-page",
    image: "assets/s-images/premier-lading-page.png",
    video: "assets/s-video/premier.mp4",
  },
  {
    id: 17,
    title: "Modern Landing Page",
    desc: "Landing page with CTA & hero banner.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/09-Landing-page/PROJECT_1",
    image: "assets/s-images/modern landing page -lightly padded.png",
    video: "assets/s-video/modern-landing-page.mp4",
  },
  {
    id: 18,
    title: "Nature Landing Page",
    desc: "Nature-inspired responsive landing page.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/06-Nature-Landing-page",
    image: "assets/s-images/nATURE.png",
    video: "assets/s-video/nature.mp4",
  },
  {
    id: 19,
    title: "Pinterest Clone",
    desc: "Pinterest-style masonry image grid.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/16-pintrest-clone",
    image: "assets/s-images/PINTREASDT.png",
    video: "assets/s-video/PINTREST.mp4",
  },
  {
    id: 20,
    title: "Attractive Landing Page",
    desc: "Landing page with appealing colors & spacing.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/11-attracive-landing-page",
    image: "assets/s-images/john walker.png",
    video: "assets/s-video/attractive-landing-page.mp4",
  },
  {
    id: 21,
    title: "Sidebar Menu",
    desc: "Responsive sidebar with toggle animation.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/01-sidebar-menu",
    image: "assets/s-images/SIDERBAR.png",
    video: "assets/s-video/sidebar.mp4",
  },
  {
    id: 22,
    title: "Age Calculator",
    desc: "Calculate age based on birth date.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/21-Age-calculator/",
    image: "assets/s-images/age-calculator.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 23,
    title: "Modern Calculator",
    desc: "Simple modern calculator app.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/22-Calculator/",
    image: "assets/s-images/modern-calculator.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 24,
    title: "Notes App",
    desc: "Create, edit, and delete notes.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/23-Notes/",
    image: "assets/s-images/notes.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 25,
    title: "Stopwatch",
    desc: "Basic stopwatch with start, stop, and reset.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/24-stopwatch/",
    image: "assets/s-images/stopwatch.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 26,
    title: "Digital Clock",
    desc: "Live digital clock with dynamic time display.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/25-Digital-Clock/",
    image: "assets/s-images/digital-clock.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 27,
    title: "Image Crousers",
    desc: "Image carousel slider with navigation buttons.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/26-image-crousers/",
    image: "assets/s-images/image-crousels.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 28,
    title: "Mini Calendar",
    desc: "Small interactive calendar app.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/27-Mini-calendar/",
    image: "assets/s-images/mini-calendasr.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 29,
    title: "Form Validation",
    desc: "Validate forms before submission using JS.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/28-Form-Validation/",
    image: "assets/s-images/form-validation.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 30,
    title: "Instagram Clone",
    desc: "Frontend clone of Instagram UI.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/29-insta-clone/",
    image: "assets/s-images/insta-clone.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 31,
    title: "Glitch Effect",
    desc: "Text and image glitch animation effect.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/30-Glitch-effect/",
    image: "assets/s-images/glitch.png",
    video: "assets/s-video/default.mp4",
  },
  {
    id: 32,
    title: "Job Dashboard",
    desc: "Dashboard UI for job applications.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/31-job%20dashboard/",
    image: "assets/s-images/job-dashboard.png",
    video: "assets/s-video/default.mp4",
  },
];
