const projectsData = [
  // 1 - 32 (original items) — all categories set to "html-css"
  {
    id: 1,
    title: "FilmyWorld Movie App",
    desc: "React movie app with Redux and infinite scrolling.",
    category: "html-css",
    link: "https://react-filmyworld.netlify.app/",
    image: "assets/s-images/filmyworld.png",
    video: "assets/s-video/Filmy-World.mp4",
  },
  {
    id: 2,
    title: "React E-Commerce App",
    desc: "React e-commerce app with Context API and CRUD.",
    category: "html-css",
    link: "https://reactproject-with-api.netlify.app/",
    image: "assets/s-images/REACT-2.png",
    video: "assets/s-video/react-e-comerce.mp4",
  },
  {
    id: 3,
    title: "Dribbble Clone",
    desc: "Dribbble-style grid portfolio layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/13-dribble-clone",
    image: "assets/s-images/DRIBBLE.png",
    video: "assets/s-video/dribble.mp4",
  },
  {
    id: 4,
    title: "Winter Icecream Page",
    desc: "Icecream-themed landing page with animations.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/05-WINTER-SPECIAL-ICECREAM",
    image: "assets/s-images/ICECREAM.png",
    video: "assets/s-video/icecream.mp4",
  },
  {
    id: 5,
    title: "E-Commerce Landing",
    desc: "Basic e-commerce homepage with responsive layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/03-Ecommerce",
    image: "assets/s-images/CARA ATTRASCTIVE.png",
    video: "assets/s-video/cara.mp4",
  },
  {
    id: 6,
    title: "Blinkit UI Clone",
    desc: "Blinkit UI clone using grid & flexbox.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/02-blinkit-clone",
    image: "assets/s-images/BLINKIT.png",
    video: "assets/s-video/blinkit.mp4",
  },
  {
    id: 7,
    title: "e_learning Landing Page",
    desc: "Clean modern landing page with hero section.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/04-Landing-page",
    image: "assets/s-images/E-LEARNING.png",
    video: "assets/s-video/e-learning.mp4",
  },
  {
    id: 8,
    title: "Obys Agency Clone",
    desc: "Agency landing page with smooth sections.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/14-obys-agency-clone",
    image: "assets/s-images/OBYS.png",
    video: "assets/s-video/obys-agency.mp4",
  },
  {
    id: 9,
    title: "Product Designer Page",
    desc: "Portfolio-style page for designers.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/15-product-designer",
    image: "assets/s-images/producr-designere.png",
    video: "assets/s-video/product-designer.mp4",
  },
  {
    id: 10,
    title: "Porsche Landing Page",
    desc: "Car landing page with carousel hero.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/07-Porsche",
    image: "assets/s-images/PORSCHE.png",
    video: "assets/s-video/porshce.mp4",
  },
  {
    id: 11,
    title: "Cotton Landing Page",
    desc: "Cotton product page with clean layout.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/10-cotton-landing-page",
    image: "assets/s-images/cotton ladning page.png",
    video: "assets/s-video/cotton-landing-page.mp4",
  },
  {
    id: 12,
    title: "Hero Panther Page",
    desc: "Bold hero section inspired by Panther theme.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/20-Hero-Panther-landing-page",
    image: "assets/s-images/MARVEL.png",
    video: "assets/s-video/black-panther.mp4",
  },
  {
    id: 13,
    title: "Sheriyans Landing Page",
    desc: "Clean landing page with good typography.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/18-sheriyans-landig-page",
    image: "assets/s-images/sheriyans .png",
    video: "assets/s-video/sheriyans.mp4",
  },
  {
    id: 14,
    title: "Play Landing Page",
    desc: "Colorful landing page with fun elements.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/19-PLAY-landing-pages/",
    image: "assets/s-images/PLAY-KLANDINMG.png",
    video: "assets/s-video/play.mp4",
  },
  {
    id: 15,
    title: "Starbucks Landing Page",
    desc: "Starbucks-themed page with product showcase.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/08-Starbucks",
    image: "assets/s-images/STARBUCKS.png",
    video: "assets/s-video/starbucks.mp4",
  },
  {
    id: 16,
    title: "Premier Landing Page",
    desc: "Premium look landing page with hover effects.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/12-Premier landing-page",
    image: "assets/s-images/premier-lading-page.png",
    video: "assets/s-video/premier.mp4",
  },
  {
    id: 17,
    title: "Modern Landing Page",
    desc: "Landing page with CTA & hero banner.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/09-Landing-page/PROJECT_1",
    image: "assets/s-images/modern landing page -lightly padded.png",
    video: "assets/s-video/modern-landing-page.mp4",
  },
  {
    id: 18,
    title: "Nature Landing Page",
    desc: "Nature-inspired responsive landing page.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/06-Nature-Landing-page",
    image: "assets/s-images/nATURE.png",
    video: "assets/s-video/nature.mp4",
  },
  {
    id: 19,
    title: "Pinterest Clone",
    desc: "Pinterest-style masonry image grid.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/16-pintrest-clone",
    image: "assets/s-images/PINTREASDT.png",
    video: "assets/s-video/PINTREST.mp4",
  },
  {
    id: 20,
    title: "Attractive Landing Page",
    desc: "Landing page with appealing colors & spacing.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/11-attracive-landing-page",
    image: "assets/s-images/john walker.png",
    video: "assets/s-video/attractive-landing-page.mp4",
  },
  {
    id: 21,
    title: "Sidebar Menu",
    desc: "Responsive sidebar with toggle animation.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/01-sidebar-menu",
    image: "assets/s-images/SIDERBAR.png",
    video: "assets/s-video/sidebar.mp4",
  },
  {
    id: 22,
    title: "Age Calculator",
    desc: "Calculate age based on birth date.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/21-Age-calculator/",
    image: "assets/s-images/age-calculator.png",
    video: "assets/s-video/age-calculator.mp4",
  },
  {
    id: 23,
    title: "Modern Calculator",
    desc: "Simple modern calculator app.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/22-Calculator/",
    image: "assets/s-images/modern-calculator.png",
    video: "assets/s-video/modern-calculator.mp4",
  },
  {
    id: 24,
    title: "Notes App",
    desc: "Create, edit, and delete notes.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/23-Notes/",
    image: "assets/s-images/notes.png",
    video: "assets/s-video/notes.mp4",
  },
  {
    id: 25,
    title: "Stopwatch",
    desc: "Basic stopwatch with start, stop, and reset.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/24-stopwatch/",
    image: "assets/s-images/stopwatch.png",
    video: "assets/s-video/stopwatch.mp4",
  },
  {
    id: 26,
    title: "Digital Clock",
    desc: "Live digital clock with dynamic time display.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/25-Digital-Clock/",
    image: "assets/s-images/digital-clock.png",
    video: "assets/s-video/digital-clock.mp4",
  },
  {
    id: 27,
    title: "Image Crousers",
    desc: "Image carousel slider with navigation buttons.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/26-image-crousers/",
    image: "assets/s-images/image-crousels.png",
    video: "assets/s-video/image-crousels.mp4",
  },
  {
    id: 28,
    title: "Mini Calendar",
    desc: "Small interactive calendar app.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/27-Mini-calendar/",
    image: "assets/s-images/mini-calendasr.png",
    video: "assets/s-video/mini calendar.mp4",
  },
  {
    id: 29,
    title: "Form Validation",
    desc: "Validate forms before submission using JS.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/28-Form-Validation/",
    image: "assets/s-images/form-validation.png",
    video: "assets/s-video/form-validation.mp4",
  },
  {
    id: 30,
    title: "Instagram Clone",
    desc: "Frontend clone of Instagram UI.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/29-insta-clone/",
    image: "assets/s-images/insta-clone.png",
    video: "assets/s-video/insta-clone.mp4",
  },
  {
    id: 31,
    title: "Glitch Effect",
    desc: "Text and image glitch animation effect.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/30-Glitch-effect/",
    image: "assets/s-images/glitch.png",
    video: "assets/s-video/glitch-effect.mp4",
  },
  {
    id: 32,
    title: "Job Dashboard",
    desc: "Dashboard UI for job applications.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/31-job%20dashboard/",
    image: "assets/s-images/job-dashboard.png",
    video: "assets/s-video/job-dashboard.mp4",
  },


  {
    id: 33,
    title: "Vita Health Care",
    desc: "Health care landing page with services section.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/32-Health-care/",
    image: "assets/s-images/vita-health-care.png",
    video: "assets/s-video/vita-health-care.mp4",
  },
  {
    id: 34,
    title: "Insta Reel Clone",
    desc: "Short video reel style UI inspired by Instagram Reels.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/33-insta-reel-clone/",
    image: "assets/s-images/insta-reel-clone.png",
    video: "assets/s-video/insta-reel-clone.mp4",
  },
  {
    id: 35,
    title: "CineScope (Movie App)",
    desc: "Movie listing UI with search and filters.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/34-CineScope-Movie/",
    image: "assets/s-images/cinescope.png",
    video: "assets/s-video/cinescope.mp4",
  },
  {
    id: 36,
    title: "CashFlow (Expense Tracker)",
    desc: "Expense tracker app to add and categorize expenses.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/35-CashFlow-expense-Tracker/",
    image: "assets/s-images/cashflow.png",
    video: "assets/s-video/cashflow.mp4",
  },
  {
    id: 37,
    title: "TaskMaker (Trello-like App)",
    desc: "Project board with draggable cards and lists.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/36-TaskMaker-project/",
    image: "assets/s-images/taskmaker.png",
    video: "assets/s-video/taskmaker.mp4",
  },
  {
    id: 38,
    title: "TravelGo",
    desc: "Travel planning landing page with destinations showcase.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/37-TravelPlan",
    image: "assets/s-images/travelgo.png",
    video: "assets/s-video/travelgo.mp4",
  },
  {
    id: 39,
    title: "API Master (Postman Clone)",
    desc: "API testing UI with request builder and response viewer.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/38-Postman",
    image: "assets/s-images/api-master.png",
    video: "assets/s-video/api-master.mp4",
  },
  {
    id: 40,
    title: "CodeCraft (Live Preview Editor)",
    desc: "Live code editor with HTML/CSS/JS preview pane.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/39-Website-Live-Preview",
    image: "assets/s-images/codecraft.png",
    video: "assets/s-video/codecraft.mp4",
  },
  {
    id: 41,
    title: "TypeBlitz",
    desc: "Typing practice app to measure speed & accuracy.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/40-Typing-Master",
    image: "assets/s-images/typeblitz.png",
    video: "assets/s-video/typeblitz.mp4",
  },
  {
    id: 42,
    title: "JobFinder (Job Portal)",
    desc: "Job listings UI with filters and apply CTA.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/41-Job-Finder",
    image: "assets/s-images/jobfinder.png",
    video: "assets/s-video/jobfinder.mp4",
  },
  {
    id: 43,
    title: "DreamHome (Real Estate)",
    desc: "Property listing layout with gallery and details.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/42-Property-Dealer",
    image: "assets/s-images/dreamhome.png",
    video: "assets/s-video/dreamhome.mp4",
  },
  {
    id: 44,
    title: "SkillSpire (E-Learning)",
    desc: "Course marketplace landing page with pricing.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/43-Course-Selling",
    image: "assets/s-images/skillspire.png",
    video: "assets/s-video/skillspire.mp4",
  },
  {
    id: 45,
    title: "DriveX (Car Rental)",
    desc: "Car rental landing page with booking CTA.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/44-Car-Rental-Drivex",
    image: "assets/s-images/drivex.png",
    video: "assets/s-video/drivex.mp4",
  },
  {
    id: 46,
    title: "NeonArt (NFT Marketplace)",
    desc: "NFT marketplace landing UI with product cards.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/45-Neon-Selling-Website",
    image: "assets/s-images/neonart.png",
    video: "assets/s-video/neonart.mp4",
  },
  {
    id: 47,
    title: "LensLoop (Photography App)",
    desc: "Image gallery and search UI inspired by Unsplash.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/46-Lensloop-(unplash-clone)",
    image: "assets/s-images/lensloop.png",
    video: "assets/s-video/lensloop.mp4",
  },
  {
    id: 48,
    title: "CoinDash (Crypto Dashboard)",
    desc: "Crypto dashboard UI with charts and market overview.",
    category: "js",
    link: "https://maheshkrsaw.github.io/DesignCraft75/47-CoinDash-(Binance)",
    image: "assets/s-images/coindash.png",
    video: "assets/s-video/coindash.mp4",
  },
  {
    id: 49,
    title: "BrainWave (GPT Clone)",
    desc: "Chat UI for AI assistant prototype.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/48-BrainWave-(GptClone)",
    image: "assets/s-images/brainwave.png",
    video: "assets/s-video/brainwave.mp4",
  },
  {
    id: 50,
    title: "GameZone (Esports Platform)",
    desc: "Esports landing page and tournament showcase.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/49-Gamezone",
    image: "assets/s-images/gamezone.png",
    video: "assets/s-video/gamezone.mp4",
  },
  {
    id: 51,
    title: "StreamX (Netflix Clone)",
    desc: "Video streaming UI with featured carousel.",
    category: "html-css",
    link: "https://maheshkrsaw.github.io/DesignCraft75/50-StreamX-(netflix)",
    image: "assets/s-images/streamx.png",
    video: "assets/s-video/streamx.mp4",
  },
];
